version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  astro:
    build: .
    container_name: astro-app
    ports:
      - "3000:4321"
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules

    networks:
      - app-network
    command: ["npm", "run", "dev", "--", "--host"]

  nginx:
    image: nginx:alpine
    depends_on:
      - astro
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - app-network

volumes:
  node_modules_cache:
